# ================================
# Model Arguments
# ================================
model_name_or_path: /path/to/gemma-2-9b-it/
torch_dtype: null
attn_implementation: eager

# ================================
# Data & Preprocessing
# ================================
chat_template: "{{ bos_token }}{% if messages[0]['role'] == 'system' %}{% set system_message = messages[0]['content'] | trim + '\n\n' %}{% set messages = messages[1:] %}{% else %}{% set system_message = '' %}{% endif %}{% for message in messages %}{% if loop.index0 == 0 %}{% set content = system_message + message['content'] %}{% else %}{% set content = message['content'] %}{% endif %}{% if (message['role'] == 'assistant') %}{% set role = 'model' %}{% else %}{% set role = message['role'] %}{% endif %}{{ '<start_of_turn>' + role + '\n' + content | trim + '<end_of_turn>\n' }}{% endfor %}{% if add_generation_prompt %}{{'<start_of_turn>model\n'}}{% endif %}"

dataset_mixer:
  /path/to/data/mnpo_iter1/pref: 1.0

dataset_splits:
  - train

preprocessing_num_workers: 12

# ================================
# Training Parameters
# ================================
bf16: true
eta: 0.0075
ratio: 0.3333
max_history_t: 2
beta: 10
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.1
optim: adamw_torch
seed: 42

gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

num_train_epochs: 1
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
max_length: 2048
max_prompt_length: 1800

# ================================
# Evaluation & Logging
# ================================
do_eval: false
logging_steps: 5
log_level: info
#eval_steps: 5
#metric_for_best_model: eval_loss
#load_best_model_at_end: true

# ================================
# Saving & Reporting
# ================================
save_strategy: "no"
save_total_limit: 1
push_to_hub: false

report_to:
  - wandb

# ================================
# Output
# ================================
output_dir: /path/to/outputs/gemma-2-9b-it_mnpo_stage_1_armo
run_name: gemma-2-9b-it_mnpo_stage_1_armo
